# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b79a879c1cfaf66ce8194bffc2b3379d5a5c1425fece9695fe36f584116b8762ea995f11a42bcfe06ac9bc53e884d02004b5603d11d28994a83a4bb684f08da9

test:
  secret_key_base: 58ac095fe307040be1edbb046a3d0157cda5394a34ede39b813eb0114b59c9319591bc1aae2fe985bf92d54bb610a1bf7171a4174680c168cd48a3fc70303360

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
